import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#2a8609',
        'secondary-fixed-dim': '#bfc7d2',
        'error': '#ba1a1a',
        'surface-container-high': '#e6e8e9',
        'on-primary-container': '#fffbff',
        'surface-tint': '#D44E98',
        'on-background': '#191c1d',
        'on-primary': '#ffffff',
        'surface': '#f8fafb',
        'surface-container-low': '#f2f4f5',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#404751',
        'on-secondary-fixed': '#141c25',
        'primary-container': '#D44E98',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#99fa76',
        'secondary': '#575f69',
        'surface-variant': '#e1e3e4',
        'on-tertiary-container': '#f8ffee',
        'inverse-surface': '#2e3132',
        'tertiary-fixed-dim': '#7edc5d',
        'inverse-primary': '#ffb0d0',
        'primary-fixed': '#ffd8e6',
        'surface-bright': '#f8fafb',
        'on-surface-variant': '#554149',
        'primary': '#D44E98',
        'surface-dim': '#d8dadb',
        'on-tertiary-fixed-variant': '#145200',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed': '#dbe3ef',
        'on-tertiary-fixed': '#042100',
        'tertiary': '#1c6a00',
        'primary-fixed-dim': '#ffb0d0',
        'secondary-container': '#dbe3ef',
        'inverse-on-surface': '#eff1f2',
        'on-primary-fixed-variant': '#D44E98',
        'background': '#f8fafb',
        'on-secondary-container': '#5d656f',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191c1d',
        'surface-container': '#eceeef',
        'outline': '#88717a',
        'on-primary-fixed': '#3d0023',
        'on-error-container': '#93000a',
        'outline-variant': '#dbbfc9',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Plus Jakarta Sans', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
